# Generated by Django 5.1.3 on 2024-12-05 22:34

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=350)),
                ('description', models.TextField()),
                ('bathroom', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('location', models.CharField(max_length=350)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('Room', 'Room'), ('Apartment', 'Apartment'), ('Cabin', 'Cabin'), ('Beach House', 'Beach House'), ('Mansion', 'Mansion'), ('CountrySide', 'CountrySide'), ('Lake House', 'Lake House'), ('Castle', 'Castle'), ('Camper', 'Camper')], max_length=200)),
                ('guest', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('images', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
