# Generated by Django 5.1.3 on 2024-12-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_apartment_facilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
