# Generated by Django 5.1.3 on 2024-12-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_favoriteapartment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteApartment',
        ),
    ]
