# Generated by Django 5.1.3 on 2024-12-06 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_delete_favoriteapartment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='favorited',
            field=models.ManyToManyField(blank=True, related_name='favorited_apartments', to=settings.AUTH_USER_MODEL),
        ),
    ]
