import type { Metadata } from 'next'
import { Inter,Plus_Jakarta_Sans } from 'next/font/google'
import './globals.css'
import StoreProvider from '@/redux/store'
import { Toaster } from '@/components/ui/sonner'
import Script from 'next/script'

const inter = Plus_Jakarta_Sans({ subsets:['latin-ext'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
        {children}
        <Toaster visibleToasts={1} position='top-right' richColors />
        </StoreProvider>
        <Script
          strategy="afterInteractive" // Ensure it loads after interactive phase
          src="https://accounts.google.com/gsi/client"
          async // Mark script as async for non-blocking behavior
        />
      </body>
    </html>
  )
}
