# Generated by Django 5.1.4 on 2025-01-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='sender',
        ),
        migrations.AddField(
            model_name='notifications',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
