# Generated by Django 5.1.3 on 2025-01-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_alter_booking_booked_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booked_by',
            new_name='user',
        ),
    ]
